export const themeTokens = {
  colors: {
    bg: 'var(--color-bg)',
    bgSecondary: 'var(--color-bg-secondary)',
    primary: 'var(--color-primary)',
    primaryDark: 'var(--color-primary-dark)',
    accent: 'var(--color-accent)',
    accentDark: 'var(--color-accent-dark)',
    success: 'var(--color-success)',
    warning: 'var(--color-warning)',
    error: 'var(--color-error)',
    text: 'var(--color-text)',
    textLight: 'var(--color-text-light)',
    textWhite: 'var(--color-text-white)',
  },
  shadows: {
    card: 'var(--shadow-card)',
    button: 'var(--shadow-button)',
    hover: 'var(--shadow-hover)',
  },
  radius: {
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    xl: 'var(--radius-xl)',
    '2xl': 'var(--radius-2xl)',
  },
  spacing: {
    xs: 'var(--spacing-xs)',
    sm: 'var(--spacing-sm)',
    md: 'var(--spacing-md)',
    lg: 'var(--spacing-lg)',
    xl: 'var(--spacing-xl)',
    '2xl': 'var(--spacing-2xl)',
  },
  fontSize: {
    xs: 'var(--text-xs)',
    sm: 'var(--text-sm)',
    base: 'var(--text-base)',
    lg: 'var(--text-lg)',
    xl: 'var(--text-xl)',
    '2xl': 'var(--text-2xl)',
    '3xl': 'var(--text-3xl)',
    '4xl': 'var(--text-4xl)',
  },
  transition: {
    fast: 'var(--transition-fast)',
    normal: 'var(--transition-normal)',
    slow: 'var(--transition-slow)',
  },
} as const;
